name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Set this to the branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to GitHub Pages
      run: npm run deploy -- --dist-dir dist


    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '20.13.1'  # Use the version you prefer

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
